import crypto from 'crypto';
import fs from 'fs';
import path from 'path';
import https from 'https';
import http from 'http';

export default async function handler(req, res) {
  const { token, expires } = req.query;
  const SECRET = process.env.API_SECRET;

  if (token && expires) {
    const expectedToken = crypto.createHmac('sha256', SECRET).update(`playlist:${expires}`).digest('hex');
    if (token !== expectedToken) return res.status(403).send('Invalid token');
    if (Date.now() > parseInt(expires)) return res.status(403).send('Token expired');
  } else if (req.headers['x-api-key'] === SECRET) {
    // Valid
  } else {
    return res.status(404).send('Not found');
  }

  try {
    // Load local channels
    const channelsPath = path.join(process.cwd(), 'data', 'channels.json');
    let allChannels = [];
    
    if (fs.existsSync(channelsPath)) {
      allChannels = JSON.parse(fs.readFileSync(channelsPath, 'utf-8'));
    }

    // Load external sources
    const sourcesPath = path.join(process.cwd(), 'data', 'sources.json');
    if (fs.existsSync(sourcesPath)) {
      const sources = JSON.parse(fs.readFileSync(sourcesPath, 'utf-8'));
      
      for (const source of sources) {
        if (!source.enabled) continue;
        
        try {
          console.log(`Fetching: ${source.name} - ${source.url}`);
          const content = await fetchUrl(source.url);
          const parsed = parseM3U(content);
          
          // Merge channels from external source
          for (const ch of parsed) {
            const existing = allChannels.find(c => c.id === ch.id);
            if (existing) {
              // Add new servers
              const existingUrls = (existing.servers || []).map(s => s.url);
              for (const srv of (ch.servers || [])) {
                if (!existingUrls.includes(srv.url)) {
                  existing.servers = existing.servers || [];
                  existing.servers.push(srv);
                }
              }
            } else {
              // New channel
              ch.group = source.name; // Tag with source name
              allChannels.push(ch);
            }
          }
          console.log(`  Added from ${source.name}: ${parsed.length} channels`);
        } catch (e) {
          console.log(`  Failed to fetch ${source.name}: ${e.message}`);
        }
      }
    }

    // Generate M3U playlist
    let playlist = '#EXTM3U\n# Playlist generated by Chill Box\n';
    
    for (const ch of allChannels) {
      if (ch.servers && ch.servers.length > 0) {
        for (const server of ch.servers) {
          playlist += `#EXTINF:-1 tvg-language="${ch.language || ''}" tvg-logo="${ch.logo || ''}" group-title="${ch.group || 'Chill Box'}" server-name="${server.name}",${ch.name}\n`;
          playlist += `#KODIPROP:inputstream.adaptive.license_type=${server.drm || ''}\n`;
          playlist += `#KODIPROP:inputstream.adaptive.license_key=${server.license || ''}\n`;
          playlist += `${server.url}\n`;
        }
      } else if (ch.url) {
        playlist += `#EXTINF:-1 tvg-language="${ch.language || ''}" tvg-logo="${ch.logo || ''}" group-title="${ch.group || 'Chill Box'}",${ch.name}\n`;
        playlist += `#KODIPROP:inputstream.adaptive.license_type=${ch.drm || ''}\n`;
        playlist += `#KODIPROP:inputstream.adaptive.license_key=${ch.license || ''}\n`;
        playlist += `${ch.url}\n`;
      }
    }

    res.setHeader('Content-Type', 'audio/x-mpegurl');
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.status(200).send(playlist);
    
  } catch (e) {
    res.status(500).json({ error: e.message });
  }
}

function fetchUrl(url) {
  return new Promise((resolve, reject) => {
    const client = url.startsWith('https') ? https : http;
    client.get(url, { headers: { 'User-Agent': 'ChillBox/1.0' } }, (response) => {
      let data = '';
      response.on('data', chunk => data += chunk);
      response.on('end', () => resolve(data));
      response.on('error', reject);
    }).on('error', reject);
  });
}

function parseM3U(content) {
  const lines = content.split('\n');
  const channels = {};
  let cur = { name: '', logo: null, group: 'Chill Box', language: '', clearKey: null, url: null, serverName: null };

  for (const line of lines) {
    const l = line.trim();
    if (l.startsWith('#EXTINF:')) {
      if (cur.url && cur.name) addChannel(channels, cur);
      cur = {
        name: (l.match(/,(.+)$/) || ['', 'Unknown'])[1].trim(),
        logo: (l.match(/tvg-logo="([^"]+)"/) || [])[1] || null,
        group: (l.match(/group-title="([^"]+)"/) || [])[1] || 'Chill Box',
        language: (l.match(/tvg-language="([^"]+)"/) || [])[1] || '',
        clearKey: null, url: null,
        serverName: (l.match(/server-name="([^"]+)"/) || [])[1] || null
      };
    } else if (l.startsWith('#KODIPROP:') && l.includes('license_key=')) {
      cur.clearKey = l.split('license_key=')[1]?.trim();
    } else if ((l.startsWith('https://') || l.startsWith('http://')) && !l.startsWith('#')) {
      cur.url = l;
      if (cur.name) {
        addChannel(channels, cur);
        cur = { name: '', logo: null, group: 'Chill Box', language: '', clearKey: null, url: null, serverName: null };
      }
    }
  }
  if (cur.url && cur.name) addChannel(channels, cur);
  return Object.values(channels);
}

function addChannel(dict, ch) {
  const base = ch.name.replace(/\s*HD$/i, '').trim();
  const srv = {
    name: ch.serverName || (ch.name.includes('HD') ? 'HD' : 'SD'),
    url: ch.url,
    drm: ch.clearKey ? 'clearkey' : '',
    license: ch.clearKey || ''
  };
  
  if (!dict[base]) {
    dict[base] = {
      id: base.toLowerCase().replace(/[^a-z0-9_]/g, '_'),
      name: base,
      language: ch.language,
      logo: ch.logo,
      group: ch.group,
      servers: [srv]
    };
  } else {
    if (!dict[base].servers.some(s => s.url === ch.url)) {
      dict[base].servers.push(srv);
    }
  }
}
